version: "3.7"

services:
  php:
    image: oxid:latest
    ports:
    - '8080:80'
    depends_on:
      - database
    extra_hosts:
      - "host.internal.docker:host-gateway"
    env_file:
      - .env.docker
    volumes:
    - ./app:/app
    - ./docker/apache/conf/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
    - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./docker/apache/conf/mods-enabled/rewrite.load:/etc/apache2/mods-enabled/rewrite.load
    - ./docker/apache/conf/apache2.conf:/etc/apache2/apache2.conf

  database:
    image: mysql:5.7.37
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: main_oxid
      MYSQL_DATABASE: main_oxid
      MYSQL_USER: main_oxid
      MYSQL_PASSWORD: main_oxid
    volumes:
    - ./databases/mariadb:/var/lib/mysql
