<?php

class exonn_connector_extend_order extends exonn_connector_extend_order_parent
{

    public function execute ()
    {
        //diese einstellung wird in config.inc.php definiert!!!
        if (!$this->getConfig()->getConfigParam('EXONN_CONNECTOR_KREDITLIMIT_ACTIV')) {
            return parent::execute();
        }

        $paymentId = oxRegistry::getSession()->getBasket()->getPaymentId();
        if($paymentId != 'oxidinvoice' && $paymentId != 'd969f84276cb4e163be009912a5f52cf' && $paymentId != 'oxiddebitnote'){
            return parent::execute();
        }

        /** @var User $oUser */
        $oUser= $this->getUser();
        /** @var Credit $creditInformation */
        $creditInformation = $oUser->getCustomerCredit();

        if(!$creditInformation["isCreditLimitAcceptable"]){
            $exceptionToDisplay = oxNew("oxexceptiontodisplay");
            $exceptionToDisplay->setMessage(oxRegistry::getLang()->translateString('INVOICE_PAYMENT_CREDIT_LIMIT_NOT_ACCEPTABLE'));
            oxRegistry::get("oxUtilsView")->addErrorToDisplay($exceptionToDisplay);
            return;
        }

        return parent::execute(); // TODO: Change the autogenerated stub
    }



}
